name: Publish mod to several platforms
on:
  workflow_call:
    inputs:
      workflow_ref:
        description: Reference for this workflow to pin version-dependent calls
        required: true
        type: string
      release_tag:
        description: The tag with associated release (e.g. v1.2.3)
        required: true
        type: string
      dry_run:
        description: If true, the files wont be published and the configuration will be logged instead.
        required: false
        default: false
        type: boolean
      sequential_publication:
        description: If true, publications will be performed sequentially.
        required: false
        default: false
        type: boolean
    secrets:
      CURSEFORGE_API_KEY:
        required: false
      MODRINTH_API_KEY:
        required: false
      DISCORD_WEBHOOK_URL:
        required: false

env:
  MOD_PUBLISH_JAVA_VERSION: 25
  GRADLE_BUILD_CACHE_PATH: ~/.gradle/caches/build-cache-1
  GRADLE_BUILD_CACHE_KEY: gradle-buildcache-${{ github.run_id }}-${{ github.run_attempt }}

permissions:
  contents: read

jobs:
  # Constructs matrix for creating GitHub Worklfow jobs
  prepare-matrix:
    runs-on: ubuntu-latest
    name: Compute the publish matrix
    outputs:
      version: ${{ steps.extract_version.outputs.version }}
      artifact_ids: ${{ steps.matrix.outputs.artifact_ids }}
      curseforge_enabled: ${{ steps.matrix.outputs.curseforge_enabled }}
      modrinth_enabled: ${{ steps.matrix.outputs.modrinth_enabled }}
      discord_enabled: ${{ steps.matrix.outputs.discord_enabled }}
    steps:
      - name: Checkout the main branch in caller repository
        # Checksout the mod repository at the release tag - this will provide the configuration
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.release_tag }}
          sparse-checkout: /publish.config.json
          sparse-checkout-cone-mode: false
          path: repository

      - name: Extract version without 'v' prefix
        id: extract_version
        env:
          RELEASE_TAG: ${{ inputs.release_tag }}
        run: |
          echo "version=${RELEASE_TAG#v}" >> "$GITHUB_OUTPUT"

      - name: Compute artifact matrix and enabled platforms
        id: matrix
        run: |
          set -euo pipefail
          CONFIG=repository/publish.config.json
          echo "artifact_ids=$(jq -c '.artifacts | keys_unsorted' "$CONFIG")" >> "$GITHUB_OUTPUT"
          echo "curseforge_enabled=$(jq -r '.curseforge_enabled' "$CONFIG")" >> "$GITHUB_OUTPUT"
          echo "modrinth_enabled=$(jq -r '.modrinth_enabled' "$CONFIG")" >> "$GITHUB_OUTPUT"
          echo "discord_enabled=$(jq -r '.discord_enabled' "$CONFIG")" >> "$GITHUB_OUTPUT"

  prepare-assets:
    runs-on: ubuntu-latest
    name: Download release assets and prepare publish workspace
    steps:
      - name: Checkout the main branch in caller repository
        # Checksout the mod repository at the release tag - this will provide the configuration
        uses: actions/checkout@v7
        with:
          ref: ${{ inputs.release_tag }}
          sparse-checkout: /publish.config.json
          sparse-checkout-cone-mode: false
          path: repository

      - name: Checkout workflow repository
        # Checksout the repository of this workflow to use the files
        uses: actions/checkout@v7
        with:
          repository: lukaskabc/Minecraft-Mod-Publish-Workflows
          ref: ${{ inputs.workflow_ref }}
          path: workflow
          fetch-depth: 1

      - name: Download release assets
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          TARGET_DIR: 'workflow/publish/artifacts'
          RELEASE_TAG: ${{ inputs.release_tag }}
        run: |
          gh release download "$RELEASE_TAG" --dir "$TARGET_DIR" --pattern "*.jar"
          ls -la "$TARGET_DIR"

      - name: Save release description to changelog.md
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ inputs.release_tag }}
        run: |
          gh release view "$RELEASE_TAG" --json body --jq '.body' > workflow/publish/changelog.md

      - name: Generate GitHub publish result JSON
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ inputs.release_tag }}
        run: |
          # Create target directories
          mkdir -p workflow/publish/build/publishMods
          
          # Fetch release details and construct the JSON structure dynamically
          gh release view "$RELEASE_TAG" --json databaseId,name | jq \
            --arg repo "$GH_REPO" \
            --arg tag "$RELEASE_TAG" \
            '{
              type: "github",
              repository: $repo,
              releaseId: .databaseId,
              url: "https://github.com/\($repo)/releases/tag/\($tag)",
              title: "GitHub: \(.name)"
            }' > workflow/publish/build/publishMods/github-publish-result.json

      - name: Prepare gradle wrapper
        run: chmod +x workflow/publish/gradlew

      - name: Upload publish workspace
        # Give access to files for upcoming jobs
        uses: actions/upload-artifact@v7
        with:
          name: publish-workspace
          path: |
            workflow/
            repository/publish.config.json
          retention-days: 1

  prepare-buildsrc:
    # Only needed to warm the Gradle build cache when running sequentially
    if: inputs.sequential_publication
    runs-on: ubuntu-latest
    name: Pre-build buildSrc and warm Gradle cache
    steps:
      - name: Checkout workflow repository
        # Checksout the repository of this workflow to use the files
        uses: actions/checkout@v7
        with:
          repository: lukaskabc/Minecraft-Mod-Publish-Workflows
          ref: ${{ inputs.workflow_ref }}
          path: workflow
          fetch-depth: 1

      - name: Prepare gradle wrapper
        run: chmod +x workflow/publish/gradlew

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.MOD_PUBLISH_JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-cleanup: on-success
          cache-read-only: false
          cache-write-only: false

      - name: Pre-build buildSrc
        working-directory: workflow/publish
        run: ./gradlew clean build -p buildSrc

      - name: Save Gradle build cache
        uses: actions/cache/save@v6
        with:
          path: ${{ env.GRADLE_BUILD_CACHE_PATH }}
          key: ${{ env.GRADLE_BUILD_CACHE_KEY }}

  publish-curseforge:
    needs: [prepare-matrix, prepare-assets, prepare-buildsrc]
    if: |
      !cancelled() &&
      needs.prepare-matrix.result == 'success' &&
      needs.prepare-assets.result == 'success' &&
      (needs.prepare-buildsrc.result == 'success' || needs.prepare-buildsrc.result == 'skipped') &&
      needs.prepare-matrix.outputs.curseforge_enabled == 'true'
    runs-on: ubuntu-latest
    name: ${{ matrix.id }} - Publish to CurseForge
    permissions: {}
    strategy:
      # Allow some tasks to succeed and do not cancel others if one fails
      fail-fast: false
      max-parallel: ${{ inputs.sequential_publication && 1 || 100 }} # run sequentially
      matrix:
        id: ${{ fromJson(needs.prepare-matrix.outputs.artifact_ids) }}
    steps:
      - name: Download publish workspace
        uses: actions/download-artifact@v8
        with:
          name: publish-workspace

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.MOD_PUBLISH_JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: 'true'

      - name: Restore Gradle build cache
        if: inputs.sequential_publication
        uses: actions/cache/restore@v6
        with:
          path: ${{ env.GRADLE_BUILD_CACHE_PATH }}
          key: ${{ env.GRADLE_BUILD_CACHE_KEY }}

      - name: ${{ matrix.id }} - Publish CurseForge artifact
        shell: bash
        env:
          CURSEFORGE_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          PLATFORM: 'curseforge'
          DRY_RUN: ${{ inputs.dry_run }}
          VERSION: ${{ needs.prepare-matrix.outputs.version }}
          ARTIFACT_ID: ${{ matrix.id }}
        run: |
          set -euo pipefail
          export CONFIG_JSON=$(cat repository/publish.config.json)
          chmod +x workflow/publish/gradlew
          cd workflow/publish
          ./gradlew publishArtifact

      - name: ${{ matrix.id }} - Upload publish mods result
        uses: actions/upload-artifact@v7
        with:
          name: modPublish-result-curseforge-${{ matrix.id }}
          path: workflow/publish/build/publishMods/*.json
          if-no-files-found: 'error'
          retention-days: 1

  publish-modrinth:
    needs: [prepare-matrix, prepare-assets, prepare-buildsrc]
    if: |
      !cancelled() &&
      needs.prepare-matrix.result == 'success' &&
      needs.prepare-assets.result == 'success' &&
      (needs.prepare-buildsrc.result == 'success' || needs.prepare-buildsrc.result == 'skipped') &&
      needs.prepare-matrix.outputs.modrinth_enabled == 'true'
    runs-on: ubuntu-latest
    name: ${{ matrix.id }} - Publish to Modrinth
    permissions: {}
    strategy:
      fail-fast: false
      max-parallel: ${{ inputs.sequential_publication && 1 || 100 }} # run sequentially
      matrix:
        id: ${{ fromJson(needs.prepare-matrix.outputs.artifact_ids) }}
    steps:
      - name: Download publish workspace
        uses: actions/download-artifact@v8
        with:
          name: publish-workspace

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.MOD_PUBLISH_JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: 'true'

      - name: Restore Gradle build cache
        if: inputs.sequential_publication
        uses: actions/cache/restore@v6
        with:
          path: ${{ env.GRADLE_BUILD_CACHE_PATH }}
          key: ${{ env.GRADLE_BUILD_CACHE_KEY }}

      - name: ${{ matrix.id }} - Publish Modrinth artifact
        shell: bash
        env:
          MODRINTH_API_KEY: ${{ secrets.MODRINTH_API_KEY }}
          PLATFORM: 'modrinth'
          DRY_RUN: ${{ inputs.dry_run }}
          VERSION: ${{ needs.prepare-matrix.outputs.version }}
          ARTIFACT_ID: ${{ matrix.id }}
        run: |
          set -euo pipefail
          export CONFIG_JSON=$(cat repository/publish.config.json)
          chmod +x workflow/publish/gradlew
          cd workflow/publish
          ./gradlew publishArtifact

      - name: ${{ matrix.id }} - Upload publish mods result
        uses: actions/upload-artifact@v7
        with:
          name: modPublish-result-modrinth-${{ matrix.id }}
          path: workflow/publish/build/publishMods/*.json
          if-no-files-found: 'error'
          retention-days: 1

  announce-discord:
    needs: [prepare-matrix, prepare-assets, prepare-buildsrc, publish-curseforge, publish-modrinth]
    # !cancelled() - run always even if a dependency "failed (checked later)" or was skipped (disabled)
    # Check that the prepare jobs succeeded
    # Check that discord is enabled
    # Check that both modrinth and curseforge jobs succeeded
    if: |
      !cancelled() &&
      needs.prepare-matrix.result == 'success' &&
      needs.prepare-assets.result == 'success' &&
      (needs.prepare-buildsrc.result == 'success' || needs.prepare-buildsrc.result == 'skipped') &&
      needs.prepare-matrix.outputs.discord_enabled == 'true' &&
      (needs.publish-curseforge.result == 'success' || needs.publish-curseforge.result == 'skipped') &&
      (needs.publish-modrinth.result == 'success' || needs.publish-modrinth.result == 'skipped')
    runs-on: ubuntu-latest
    name: Send Discord announcement
    permissions: {}
    steps:
      - name: Download publish workspace
        uses: actions/download-artifact@v8
        with:
          name: publish-workspace

      - name: Download publish results
        uses: actions/download-artifact@v8
        with:
          pattern: modPublish-result-**
          path: workflow/publish/build/publishMods
          merge-multiple: 'true'

      - name: Debug - List files
        run: |
          ls -la workflow/publish/build/publishMods/
          ls -la .

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ env.MOD_PUBLISH_JAVA_VERSION }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: 'true'

      - name: Restore Gradle build cache
        if: inputs.sequential_publication
        uses: actions/cache/restore@v6
        with:
          path: ${{ env.GRADLE_BUILD_CACHE_PATH }}
          key: ${{ env.GRADLE_BUILD_CACHE_KEY }}

      - name: Announce on Discord
        shell: bash
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          DRY_RUN: ${{ inputs.dry_run }}
          VERSION: ${{ needs.prepare-matrix.outputs.version }}
        run: |
          set -euo pipefail
          export CONFIG_JSON=$(cat repository/publish.config.json)
          chmod +x workflow/publish/gradlew
          cd workflow/publish
          ./gradlew announceDiscord