package cz.lukaskabc.minecraft.ci.publish.action

import cz.lukaskabc.minecraft.ci.publish.EnvProvider
import cz.lukaskabc.minecraft.ci.publish.ProjectConfiguration
import cz.lukaskabc.minecraft.ci.publish.schema.DiscordWebhook
import cz.lukaskabc.minecraft.ci.publish.schema.PublishConfigSchema
import org.gradle.api.logging.Logging
import org.gradle.api.provider.ProviderFactory
import org.gradle.testfixtures.ProjectBuilder
import org.junit.jupiter.api.Assumptions.assumeTrue
import org.junit.jupiter.api.DisplayName
import org.junit.jupiter.api.Test

/*
This file was generated by Claude for purposes of running a simple quick discord implementation test
 */

/**
 * Live integration test for [AnnounceDiscordAction].
 *
 * This test sends a REAL HTTP request to a REAL Discord webhook. It is
 * deliberately excluded from the normal `test` task (see build.gradle.kts)
 * and only runs via the dedicated `testDiscordAnnounce` task:
 *
 *   ./gradlew testDiscordAnnounce -PdiscordWebhookUrl="https://discord.com/api/webhooks/xxx/yyy"
 *
 * or, equivalently:
 *
 *   TEST_DISCORD_WEBHOOK_URL="https://discord.com/api/webhooks/xxx/yyy" ./gradlew testDiscordAnnounce
 *
 */
class AnnounceDiscordActionTest {

    /** Overrides only the webhook URL, everything else falls back to real env vars. */
    private class FixedUrlEnvProvider(
        providers: ProviderFactory,
        private val webhookUrl: String
    ) : EnvProvider(providers) {
        override fun discordWebhookUrl() = webhookUrl
    }

    /**
     * Writes one fake publish result per platform into `build/publishMods/`,
     * matching the JSON shapes `me.modmuss50.mpp.GithubPublishResult`,
     * `CurseForgePublishResult`, and `ModrinthPublishResult` serialize to.
     * The "type" field on each is the sealed-class discriminator that
     * `PublishResult.fromJson()` reads to pick the right subtype.
     */
    private fun writePublishResultFixtures(project: org.gradle.api.Project) {
        val publishModsDir = project.layout.buildDirectory.dir("publishMods").get().asFile
        publishModsDir.mkdirs()

        publishModsDir.resolve("github.json").writeText(
            """
            {
              "type": "github",
              "repository": "lukaskabc/example-mod",
              "releaseId": 123456789,
              "url": "https://github.com/lukaskabc/example-mod/releases/tag/v0.0.0-test",
              "title": "Test Release v0.0.0-test"
            }
            """.trimIndent()
        )

        publishModsDir.resolve("curseforge.json").writeText(
            """
            {
              "type": "curseforge",
              "projectId": "123456",
              "projectSlug": "example-mod",
              "fileId": 987654,
              "title": "Test Release v0.0.0-test"
            }
            """.trimIndent()
        )

        publishModsDir.resolve("modrinth.json").writeText(
            """
            {
              "type": "modrinth",
              "id": "AbCdEfGh",
              "projectId": "AANobbMI",
              "title": "Test Release v0.0.0-test"
            }
            """.trimIndent()
        )
    }

    @Test
    @DisplayName("sends a real announcement to the configured Discord webhook")
    fun sendsRealAnnouncement() {
        val webhookUrl = System.getProperty("test.discord.webhook.url")
        assumeTrue(!webhookUrl.isNullOrBlank()) {
            "Skipping live Discord test: no webhook URL provided. " +
                    "Run with ./gradlew testDiscordAnnounce -PdiscordWebhookUrl=<url>"
        }

        val project = ProjectBuilder.builder().build()
        project.file("changelog.md").writeText(
            """
            - Fixed a bug
            - Improved performance
            """.trimIndent()
        )
        writePublishResultFixtures(project)

        val discordWebhook = DiscordWebhook().apply {
            username = "CI Test Bot"
            releaseContent = "Test announcement for v{version}\n{changelog}"
        }

        val publishConfig = PublishConfigSchema().apply {
            this.discordWebhook = discordWebhook
        }

        val envProvider = FixedUrlEnvProvider(project.providers, webhookUrl!!)

        val configuration = ProjectConfiguration(
            project = project,
            modVersion = "0.0.0-test",
            publishConfig = publishConfig,
            logger = Logging.getLogger(AnnounceDiscordActionTest::class.java),
            envProvider = envProvider
        )

        // Throws if Discord rejects the request - that failure IS the test result.
        AnnounceDiscordAction(configuration).run()
    }
}